#lang sicp

(define (stream-car stream) (car stream))
(define (stream-cdr stream) (force (cdr stream)))

(define
  (stream-map proc . argstreams)
  (if (null? (car argstreams))
      the-empty-stream
      (cons-stream
       (apply proc (map stream-car argstreams))
       (apply stream-map
              (cons proc (map stream-cdr argstreams))))))


(define (interleave s1 s2)
  (if (stream-null? s1)
      s2
      (cons-stream (stream-car s1)
                   (interleave s2 (stream-cdr s1)))))

(define (pairs s t)
  (cons-stream
   (list (stream-car s) (stream-car t))
   (interleave
    (stream-map (lambda (x) (list (stream-car s) x)) (stream-cdr t))
    (pairs (stream-cdr s) (stream-cdr t)))))

(define (integers-starting-from n)
  (cons-stream n (integers-starting-from (+ n 1))))
(define integers (integers-starting-from 1))

(define pii (pairs integers integers))

(define (stream-ref s n)
  (if (= n 0)
      (stream-car s)
      (stream-ref (stream-cdr s) (- n 1))))

(stream-ref pii 0)
(stream-ref pii 1)
(stream-ref pii 2)
(stream-ref pii 3)
(stream-ref pii 4)
(stream-ref pii 5)
(stream-ref pii 6)
(stream-ref pii 7)
(stream-ref pii 8)
(stream-ref pii 9)
(stream-ref pii 10)
(stream-ref pii 11)
(stream-ref pii 12)
(stream-ref pii 13)
(stream-ref pii 14)
(stream-ref pii 15)
(stream-ref pii 16)
(stream-ref pii 17)
(stream-ref pii 18)
(stream-ref pii 19)
(stream-ref pii 20)
(stream-ref pii 21)
(stream-ref pii 22)
(stream-ref pii 23)
(stream-ref pii 24)
(stream-ref pii 25)
(stream-ref pii 26)
(stream-ref pii 27)
(stream-ref pii 28)
(stream-ref pii 29)
(stream-ref pii 30)
(stream-ref pii 31)
(stream-ref pii 32)
(stream-ref pii 33)
(stream-ref pii 34)
(stream-ref pii 35)
(stream-ref pii 36)
(stream-ref pii 37)
(stream-ref pii 38)
(stream-ref pii 39)
(stream-ref pii 40)
(stream-ref pii 41)
(stream-ref pii 42)
(stream-ref pii 43)
(stream-ref pii 44)
(stream-ref pii 45)
(stream-ref pii 46)
(stream-ref pii 47)
(stream-ref pii 48)
(stream-ref pii 49)
(stream-ref pii 50)
(stream-ref pii 51)
(stream-ref pii 52)
(stream-ref pii 53)
(stream-ref pii 54)
(stream-ref pii 55)
(stream-ref pii 56)
(stream-ref pii 57)
(stream-ref pii 58)
(stream-ref pii 59)
(stream-ref pii 60)
(stream-ref pii 61)
(stream-ref pii 62)
(stream-ref pii 63)
(stream-ref pii 64)
(stream-ref pii 65)
(stream-ref pii 66)
(stream-ref pii 67)
(stream-ref pii 68)
(stream-ref pii 69)
(stream-ref pii 70)
(stream-ref pii 71)
(stream-ref pii 72)
(stream-ref pii 73)
(stream-ref pii 74)
(stream-ref pii 75)
(stream-ref pii 76)
(stream-ref pii 77)
(stream-ref pii 78)
(stream-ref pii 79)
(stream-ref pii 80)
(stream-ref pii 81)
(stream-ref pii 82)
(stream-ref pii 83)
(stream-ref pii 84)
(stream-ref pii 85)
(stream-ref pii 86)
(stream-ref pii 87)
(stream-ref pii 88)
(stream-ref pii 89)
(stream-ref pii 90)
(stream-ref pii 91)
(stream-ref pii 92)
(stream-ref pii 93)
(stream-ref pii 94)
(stream-ref pii 95)
(stream-ref pii 96)
(stream-ref pii 97)
(stream-ref pii 98)
(stream-ref pii 99)
(stream-ref pii 100)
(stream-ref pii 101)
(stream-ref pii 102)
(stream-ref pii 103)
(stream-ref pii 104)
(stream-ref pii 105)
(stream-ref pii 106)
(stream-ref pii 107)
(stream-ref pii 108)
(stream-ref pii 109)
(stream-ref pii 110)
(stream-ref pii 111)
(stream-ref pii 112)
(stream-ref pii 113)
(stream-ref pii 114)
(stream-ref pii 115)
(stream-ref pii 116)
(stream-ref pii 117)
(stream-ref pii 118)
(stream-ref pii 119)
(stream-ref pii 120)
(stream-ref pii 121)
(stream-ref pii 122)
(stream-ref pii 123)
(stream-ref pii 124)
(stream-ref pii 125)
(stream-ref pii 126)
(stream-ref pii 127)
(stream-ref pii 128)
(stream-ref pii 129)
(stream-ref pii 130)
(stream-ref pii 131)
(stream-ref pii 132)
(stream-ref pii 133)
(stream-ref pii 134)
(stream-ref pii 135)
(stream-ref pii 136)
(stream-ref pii 137)
(stream-ref pii 138)
(stream-ref pii 139)
(stream-ref pii 140)
(stream-ref pii 141)
(stream-ref pii 142)
(stream-ref pii 143)
(stream-ref pii 144)
(stream-ref pii 145)
(stream-ref pii 146)
(stream-ref pii 147)
(stream-ref pii 148)
(stream-ref pii 149)
(stream-ref pii 150)
(stream-ref pii 151)
(stream-ref pii 152)
(stream-ref pii 153)
(stream-ref pii 154)
(stream-ref pii 155)
(stream-ref pii 156)
